export type Verb = {
  week: number;
  pattern: string;
  base: string;
  past: string;
  participle: string;
};

export const verbs: Verb[] = [
  { week: 1, pattern: "Sin cambios", base: "cut", past: "cut", participle: "cut" },
  { week: 1, pattern: "Sin cambios", base: "hit", past: "hit", participle: "hit" },
  { week: 1, pattern: "Sin cambios", base: "put", past: "put", participle: "put" },
  { week: 1, pattern: "Sin cambios", base: "cost", past: "cost", participle: "cost" },
  { week: 1, pattern: "Sin cambios", base: "hurt", past: "hurt", participle: "hurt" },
  { week: 1, pattern: "Sin cambios", base: "let", past: "let", participle: "let" },
  { week: 1, pattern: "Sin cambios", base: "set", past: "set", participle: "set" },
  { week: 1, pattern: "Sin cambios", base: "shut", past: "shut", participle: "shut" },
  { week: 1, pattern: "Sin cambios", base: "split", past: "split", participle: "split" },
  { week: 1, pattern: "Sin cambios", base: "spread", past: "spread", participle: "spread" },
  { week: 2, pattern: "-ought / -aught", base: "bring", past: "brought", participle: "brought" },
  { week: 2, pattern: "-ought / -aught", base: "buy", past: "bought", participle: "bought" },
  { week: 2, pattern: "-ought / -aught", base: "catch", past: "caught", participle: "caught" },
  { week: 2, pattern: "-ought / -aught", base: "teach", past: "taught", participle: "taught" },
  { week: 2, pattern: "-ought / -aught", base: "think", past: "thought", participle: "thought" },
  { week: 2, pattern: "-ought / -aught", base: "fight", past: "fought", participle: "fought" },
  { week: 3, pattern: "i -> a -> u", base: "begin", past: "began", participle: "begun" },
  { week: 3, pattern: "i -> a -> u", base: "drink", past: "drank", participle: "drunk" },
  { week: 3, pattern: "i -> a -> u", base: "ring", past: "rang", participle: "rung" },
  { week: 3, pattern: "i -> a -> u", base: "sing", past: "sang", participle: "sung" },
  { week: 3, pattern: "i -> a -> u", base: "sink", past: "sank", participle: "sunk" },
  { week: 3, pattern: "i -> a -> u", base: "swim", past: "swam", participle: "swum" },
  { week: 4, pattern: "Terminan en -t", base: "feel", past: "felt", participle: "felt" },
  { week: 4, pattern: "Terminan en -t", base: "keep", past: "kept", participle: "kept" },
  { week: 4, pattern: "Terminan en -t", base: "leave", past: "left", participle: "left" },
  { week: 4, pattern: "Terminan en -t", base: "meet", past: "met", participle: "met" },
  { week: 4, pattern: "Terminan en -t", base: "sleep", past: "slept", participle: "slept" },
  { week: 4, pattern: "Terminan en -t", base: "sweep", past: "swept", participle: "swept" },
  { week: 4, pattern: "Terminan en -t", base: "deal", past: "dealt", participle: "dealt" },
  { week: 4, pattern: "Terminan en -t", base: "lend", past: "lent", participle: "lent" },
  { week: 4, pattern: "Terminan en -t", base: "send", past: "sent", participle: "sent" },
  { week: 4, pattern: "Terminan en -t", base: "spend", past: "spent", participle: "spent" },
  { week: 5, pattern: "Participio en -en", base: "break", past: "broke", participle: "broken" },
  { week: 5, pattern: "Participio en -en", base: "choose", past: "chose", participle: "chosen" },
  { week: 5, pattern: "Participio en -en", base: "speak", past: "spoke", participle: "spoken" },
  { week: 5, pattern: "Participio en -en", base: "steal", past: "stole", participle: "stolen" },
  { week: 5, pattern: "Participio en -en", base: "freeze", past: "froze", participle: "frozen" },
  { week: 5, pattern: "Participio en -en", base: "wake", past: "woke", participle: "woken" },
  { week: 5, pattern: "Participio en -en", base: "bite", past: "bit", participle: "bitten" },
  { week: 5, pattern: "Participio en -en", base: "drive", past: "drove", participle: "driven" },
  { week: 5, pattern: "Participio en -en", base: "eat", past: "ate", participle: "eaten" },
  { week: 5, pattern: "Participio en -en", base: "write", past: "wrote", participle: "written" },
  { week: 6, pattern: "Muy usados sueltos", base: "be", past: "was/were", participle: "been" },
  { week: 6, pattern: "Muy usados sueltos", base: "go", past: "went", participle: "gone/been" },
  { week: 6, pattern: "Muy usados sueltos", base: "have", past: "had", participle: "had" },
  { week: 6, pattern: "Muy usados sueltos", base: "do", past: "did", participle: "done" },
  { week: 6, pattern: "Muy usados sueltos", base: "see", past: "saw", participle: "seen" },
  { week: 6, pattern: "Muy usados sueltos", base: "come", past: "came", participle: "come" },
  { week: 6, pattern: "Muy usados sueltos", base: "get", past: "got", participle: "got/gotten" },
  { week: 6, pattern: "Muy usados sueltos", base: "make", past: "made", participle: "made" },
  { week: 6, pattern: "Muy usados sueltos", base: "take", past: "took", participle: "taken" },
  { week: 6, pattern: "Muy usados sueltos", base: "give", past: "gave", participle: "given" },
  { week: 7, pattern: "o / ow / ew / own", base: "blow", past: "blew", participle: "blown" },
  { week: 7, pattern: "o / ow / ew / own", base: "draw", past: "drew", participle: "drawn" },
  { week: 7, pattern: "o / ow / ew / own", base: "fly", past: "flew", participle: "flown" },
  { week: 7, pattern: "o / ow / ew / own", base: "grow", past: "grew", participle: "grown" },
  { week: 7, pattern: "o / ow / ew / own", base: "know", past: "knew", participle: "known" },
  { week: 7, pattern: "o / ow / ew / own", base: "throw", past: "threw", participle: "thrown" },
  { week: 7, pattern: "o / ow / ew / own", base: "show", past: "showed", participle: "shown" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "find", past: "found", participle: "found" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "hold", past: "held", participle: "held" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "lead", past: "led", participle: "led" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "lose", past: "lost", participle: "lost" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "pay", past: "paid", participle: "paid" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "say", past: "said", participle: "said" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "sell", past: "sold", participle: "sold" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "tell", past: "told", participle: "told" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "win", past: "won", participle: "won" },
  { week: 8, pattern: "Vocal cambia, pasado = participio", base: "stand", past: "stood", participle: "stood" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "burn", past: "burnt/burned", participle: "burnt/burned" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "dream", past: "dreamt/dreamed", participle: "dreamt/dreamed" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "learn", past: "learnt/learned", participle: "learnt/learned" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "smell", past: "smelt/smelled", participle: "smelt/smelled" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "spell", past: "spelt/spelled", participle: "spelt/spelled" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "spill", past: "spilt/spilled", participle: "spilt/spilled" },
  { week: 9, pattern: "Alternativos -ed/-t", base: "spoil", past: "spoilt/spoiled", participle: "spoilt/spoiled" },
  { week: 10, pattern: "Repaso mixto", base: "become", past: "became", participle: "become" },
  { week: 10, pattern: "Repaso mixto", base: "bet", past: "bet", participle: "bet" },
  { week: 10, pattern: "Repaso mixto", base: "bleed", past: "bled", participle: "bled" },
  { week: 10, pattern: "Repaso mixto", base: "build", past: "built", participle: "built" },
  { week: 10, pattern: "Repaso mixto", base: "can", past: "could", participle: "been able to" },
  { week: 10, pattern: "Repaso mixto", base: "fall", past: "fell", participle: "fallen" },
  { week: 10, pattern: "Repaso mixto", base: "forget", past: "forgot", participle: "forgotten" },
  { week: 10, pattern: "Repaso mixto", base: "forgive", past: "forgave", participle: "forgiven" },
  { week: 10, pattern: "Repaso mixto", base: "hang", past: "hung", participle: "hung" },
  { week: 10, pattern: "Repaso mixto", base: "hear", past: "heard", participle: "heard" },
  { week: 10, pattern: "Repaso mixto", base: "hide", past: "hid", participle: "hidden" },
  { week: 10, pattern: "Repaso mixto", base: "lay", past: "laid", participle: "laid" },
  { week: 10, pattern: "Repaso mixto", base: "light", past: "lit", participle: "lit" },
  { week: 10, pattern: "Repaso mixto", base: "mean", past: "meant", participle: "meant" },
  { week: 10, pattern: "Repaso mixto", base: "read", past: "read", participle: "read" },
  { week: 10, pattern: "Repaso mixto", base: "ride", past: "rode", participle: "ridden" },
  { week: 10, pattern: "Repaso mixto", base: "rise", past: "rose", participle: "risen" },
  { week: 10, pattern: "Repaso mixto", base: "run", past: "ran", participle: "run" },
  { week: 10, pattern: "Repaso mixto", base: "shake", past: "shook", participle: "shaken" },
  { week: 10, pattern: "Repaso mixto", base: "shine", past: "shone", participle: "shone" },
  { week: 10, pattern: "Repaso mixto", base: "shoot", past: "shot", participle: "shot" },
  { week: 10, pattern: "Repaso mixto", base: "sit", past: "sat", participle: "sat" },
  { week: 10, pattern: "Repaso mixto", base: "stick", past: "stuck", participle: "stuck" },
  { week: 10, pattern: "Repaso mixto", base: "understand", past: "understood", participle: "understood" },
  { week: 10, pattern: "Repaso mixto", base: "upset", past: "upset", participle: "upset" },
  { week: 10, pattern: "Repaso mixto", base: "wear", past: "wore", participle: "worn" }
];
